language: node_js
node_js:
- '8'
before_script: npm run test
deploy:
  provider: heroku
  app: ruthless-pantocrator
  api_key:
    secure: ngHhxSe4YCnW2e/tH+Ca3FgG7GJKzC51klD/lOk4SHZdNvprl6dK5u0CmJ2HTyRQw+ERW0zTg0MLH7PXQWEh4W8o/nfv0V9bOa4iTLaNMQZQbbcBu2EkU9dTl/1joiirkAX6VAiOQwvcjhUet3n8iCA0uBPC3GhczJaMLFuxS8MJ5DBtNxDsm4Z5uK/5sWZijredz94/tqc2GeWxNq+9wKA7oPw1bvVEeQyaW/O/ZajsrtW4v2e1wRRbDpu0ZCksbhg3Sotm2P+qZmT6uRBKo5fNLVXIOCCYjPBR8I7Eih5w79tR7KHy+6dOUGQe4W3dxDq0cKKScuE3JkNuK7+Eop4Zen6n7g9U704lbRNg8auGTpGFL/n1XmoFKq8xkWOWKotFWga5kdO8vCh8RZtKiLhENLiLaP/3w0ne8USdHaFIvcM38fuCZ2F3gKK7jbw/H0dn6e3xiYIho0abRiq6FLIXROh4VbYJmksxs7gUHtI3mSi3GJ4d4A3BFHTB1Ki5XIFIu3Kl23XOHzD6GQi0H1+bPvU1DTSWMk53rSZCWFAtKs1hEiWuBBWikvBg+D28Rret2I4n7V5ejBmqarcA51bFBG8cSL/nssyA6kX3Ib8CygRxw5gklCJYE/Tx3zeoxnlAhv3LEDgcKoinb5x7E08MOUQKRrVHAPnYt7EQXHY=
